@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
ModelManager *-right-> "1" CommandHistory : records executed commands
ModelManager -down-> "1" AddressBook : current
ModelManager *-down-> "1" AddressBookVersionManager : records snapshots
AddressBookVersionManager -right-> "1..*" AddressBook : manages versions
AddressBook *-right-> "1" UniquePersonList

UniquePersonList -right-> Person

Person *--> Name
Person *--> Phone
Person *--> Level
Person *--> Class
Person *--> Assignment
}
@enduml
